In [37]:
from sklearn.decomposition import TruncatedSVD           # namely LSA/LSI(即潜在语义分析)
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

docs = ["In the middle of the night",
        "When our hopes and fears collide",
        "In the midst of all goodbyes",
        "Where all human beings lie",
        "Against another lie"]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(docs)
terms = vectorizer.get_feature_names_out()
print(terms)

['against' 'all' 'and' 'another' 'beings' 'collide' 'fears' 'goodbyes'
 'hopes' 'human' 'in' 'lie' 'middle' 'midst' 'night' 'of' 'our' 'the'
 'when' 'where']


In [38]:
n_pick_topics = 3 # 设定主题数为3
lsa = TruncatedSVD(n_pick_topics)
X2 = lsa.fit_transform(X)
X2

array([[ 8.26629804e-01, -2.46905901e-01, -3.90802643e-19],
       [ 1.02412100e-15,  1.21934586e-15,  1.00000000e+00],
       [ 8.66682085e-01, -9.09029610e-02, -3.91705460e-16],
       [ 2.80099067e-01,  7.28669961e-01, -3.28490011e-15],
       [ 1.03123637e-01,  7.63975842e-01,  4.89288897e-16]])

In [40]:
print(X.shape) # tfidf
print(X2.shape) # tfidf_lsa

(5, 20)
(5, 3)


In [42]:
test = ['against all and where']
test_tfidf = vectorizer.transform(test)
print(test_tfidf.todense())
print(lsa.transform(test_tfidf))


[[0.52335825 0.42224214 0.52335825 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.52335825]]
[[0.18866257 0.45165448 0.21366011]]


In [31]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix
import numpy as np
np.random.seed(0)
X_dense = np.random.rand(100, 100)
X_dense[:, 2 * np.arange(50)] = 0
# X = csr_matrix(X_dense)
X = X_dense
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
svd.fit(X)
X_lsa = svd.transform(X)

print(svd.explained_variance_ratio_)

print(svd.explained_variance_ratio_.sum())

print(svd.singular_values_)

[0.01570766 0.05122679 0.04998062 0.04795064 0.04539933]
0.2102650346507033
[35.24105443  4.5981613   4.54200434  4.44866153  4.32887456]


In [32]:
X.shape

(100, 100)

In [33]:
X_lsa.shape

(100, 5)