In [19]:
from sklearn.decomposition import TruncatedSVD           # namely LSA/LSI(即潜在语义分析)
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# ♪ Until the Day ♪ by JJ Lin 林俊杰
docs = ["In the middle of the night",
        "When our hopes and fears collide",
        "In the midst of all goodbyes",
        "Where all human beings lie",
        "Against another lie"]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(docs)
terms = vectorizer.get_feature_names()
print(terms)

['against', 'all', 'and', 'another', 'beings', 'collide', 'fears', 'goodbyes', 'hopes', 'human', 'in', 'lie', 'middle', 'midst', 'night', 'of', 'our', 'the', 'when', 'where']


/Users/jinrirencai/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [25]:
doc = ['against all and where']
vectorizer.transform(doc).todense()

matrix([[0.52335825, 0.42224214, 0.52335825, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.52335825]])

In [18]:
n_pick_topics = 3 # 设定主题数为3
lsa = TruncatedSVD(n_pick_topics)
X2 = lsa.fit_transform(X)
X2

array([[ 8.26629804e-01, -2.46905901e-01, -3.90802643e-19],
       [ 1.02412100e-15,  1.21934586e-15,  1.00000000e+00],
       [ 8.66682085e-01, -9.09029610e-02, -3.91705460e-16],
       [ 2.80099067e-01,  7.28669961e-01, -3.28490011e-15],
       [ 1.03123637e-01,  7.63975842e-01,  4.89288897e-16]])

In [21]:
X.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.3319971 , 0.        , 0.41150185, 0.        , 0.41150185,
         0.3319971 , 0.        , 0.6639942 , 0.        , 0.        ],
        [0.        , 0.        , 0.40824829, 0.        , 0.        ,
         0.40824829, 0.40824829, 0.        , 0.40824829, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.40824829, 0.        , 0.40824829, 0.        ],
        [0.        , 0.37601977, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.46606681, 0.        , 0.        ,
         0.37601977, 0.        , 0.        , 0.46606681, 0.        ,
         0.37601977, 0.        , 0.37601977, 0.        , 0.        ],
        [0.        , 0.38898761, 0.        , 0.        , 0.48214012,
         0.        , 0.        , 0.        , 0.        , 0.48214012,
         0.        , 0.38898761

In [9]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix
import numpy as np
np.random.seed(0)
X_dense = np.random.rand(100, 100)
X_dense[:, 2 * np.arange(50)] = 0
# X = csr_matrix(X_dense)
X = X_dense
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
svd.fit(X)
X_lsa = svd.transform(X)

print(svd.explained_variance_ratio_)

print(svd.explained_variance_ratio_.sum())

print(svd.singular_values_)

[0.01570766 0.05122679 0.04998062 0.04795064 0.04539933]
0.2102650346507033
[35.24105443  4.5981613   4.54200434  4.44866153  4.32887456]


In [12]:
X.shape

(100, 100)

In [13]:
X_lsa.shape

(100, 5)